enabled: true
gui:
  title: "&#888888» Nastavení"
  items:
    chat:
      material: OAK_SIGN
      name: "&#00fbffGlobální chat"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    msg:
      material: PAPER
      name: "&#00fbffSoukromé zprávy"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    bossbar:
      material: EMERALD
      name: "&#00fbffBossbar"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    kitOnDeath:
      material: CHAINMAIL_HELMET
      name: "&#00fbffKit po smrti"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    tpaInvites:
      material: FEATHER
      name: "&#00fbffTPA Pozvánky"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    tpaAuto:
      material: ENDER_PEARL
      name: "&#00fbffAuto TPA"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    mobSpawn:
      material: ZOMBIE_HEAD
      name: "&#00fbffMob Spawn"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
    nightVision:
      material: EYE_OF_ENDER
      name: "&#00fbffNight Vision"
      lore-enabled: "§7Stav: &#00ff44Zapnuto"
      lore-disabled: "§7Stav: &#ff0000Vypnuto"
messages:
  toggled: "&#4498DB「&#00fbff&lNASTAVENÍ&#4498DB」 &#888888» §7Změnil jsi nastavení %type% na %state%."
