enabled: true
gui:
  title: "&8Nastavení"
  items:
    chat:
      name: "&6&lCHAT"
      lore:
        - "&7Umožňuje ti vidět zprávy"
        - "&7od ostatních hráčů v chatu."
    msg:
      name: "&e&lSOUKROMÉ ZPRÁVY"
      lore:
        - "&7Umožňuje ti přijímat soukromé"
        - "&7zprávy (/msg) od hráčů."
    bossbar:
      name: "&a&lBOSSBAR"
      lore:
        - "&7Zobrazuje informační lištu"
        - "&7v horní části obrazovky."
    kitOnDeath:
      name: "&c&lKIT PO SMRTI"
      lore:
        - "&7Automaticky ti dá základní"
        - "&7vybavení po každém úmrtí."
    tpaInvites:
      name: "&b&lTPA POZVÁNKY"
      lore:
        - "&7Umožňuje ti přijímat žádosti"
        - "&7o teleportaci od hráčů."
    tpaAuto:
      name: "&d&lAUTO TPA"
      lore:
        - "&7Automaticky přijme všechny"
        - "&7příchozí žádosti o teleport."
    mobSpawn:
      name: "&2&lVIDITELNOST MOBŮ"
      lore:
        - "&7Umožňuje ti vidět efekty"
        - "&7při spawnování monster."
    nightVision:
      name: "&9&lNOČNÍ VIDĚNÍ"
      lore:
        - "&7Poskytuje permanentní efekt"
        - "&7nočního vidění."
    scoreboard:
      name: "&b&lSCOREBOARD"
      lore:
        - "&7Zobrazuje informační tabulku"
        - "&7na pravé straně obrazovky."
      command: "sb"
